###############################################################
#
# Parameter settings for the Amhara dataset
#
##############################################################

# These are the full sets of parameters used in the manuscript,
# however they are not appropriate for the demo data. 


settings_rand_a <- list(list(alarm_p = 0.2, buffer_wks = 4, max_alarm_wks = 5),
                        list(alarm_p = 0.1, buffer_wks = 4, max_alarm_wks = 5),
                        list(alarm_p = 0.05, buffer_wks = 4, max_alarm_wks = 5),
                        list(alarm_p = 0.025, buffer_wks = 4, max_alarm_wks = 5),
                        list(alarm_p = 0.012, buffer_wks = 4, max_alarm_wks = 5),
                        list(alarm_p = 0.006, buffer_wks = 4, max_alarm_wks = 5))

settings_ears_a <- list(list(method = "C1", alpha = 0.001, baseline = 7),
                        list(method = "C2", alpha = 0.001, baseline = 7),
                        list(method = "C3", alpha = 0.025, baseline = 7),
                        list(method = "C1", alpha = 0.001, baseline = 14),
                        list(method = "C2", alpha = 0.001, baseline = 14),
                        list(method = "C3", alpha = 0.025, baseline = 14),
                        list(method = "C1", alpha = 0.001, baseline = 28),
                        list(method = "C2", alpha = 0.001, baseline = 28),
                        list(method = "C3", alpha = 0.025, baseline = 28),
                        list(method = "C1", alpha = 0.001, baseline = 56),
                        list(method = "C2", alpha = 0.001, baseline = 56),
                        list(method = "C3", alpha = 0.025, baseline = 56))

settings_far_a <- list(
  #original defaults, no seasonality, no pop
  list(w = 3, b = 5, noPeriods = 1, trend = TRUE, weightsThreshold = 1, pThresholdTrend = 0.05, thresholdMethod = "delta", populationOffset = FALSE),
  #original defaults, w/ noPeriods = 4, no pop
  list(w = 3, b = 5, noPeriods = 4, trend = TRUE, weightsThreshold = 1, pThresholdTrend = 0.05, thresholdMethod = "delta", populationOffset = FALSE),
  
  #improved defaults, no seasonality, no pop
  list(w = 3, b = 5, noPeriods = 1, trend = TRUE, weightsThreshold = 2.58, pThresholdTrend = 1, pastWeeksNotIncluded = 26, populationOffset = FALSE, thresholdMethod = "nbPlugin"),
  #improved defaults, w/ noPeriods = 4, no pop
  list(w = 3, b = 5, noPeriods = 4, trend = TRUE, weightsThreshold = 2.58, pThresholdTrend = 1, pastWeeksNotIncluded = 26, populationOffset = FALSE, thresholdMethod = "nbPlugin"),
  
  #production
  list(w = 3, noPeriods = 12, trend = TRUE, pThreshold = 0, pastWeeksNotIncluded = 4, populationOffset = TRUE, thresholdMethod = "nbPlugin"),
  
  #all others (npPlugin default in my function if not given)
  list(w = 3, b = 6, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 6, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 3, b = 5, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 5, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 3, b = 4, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 4, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 3, b = 3, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 3, b = 3, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 3,        noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 3,        noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 3,        noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 5, b = 6, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 6, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 5, b = 5, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 5, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 5, b = 4, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 4, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 5, b = 3, noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 5, b = 3, noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  
  list(w = 5,        noPeriods = 12, trend = TRUE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 12, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 12, trend = FALSE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 12, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 8, trend = TRUE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 8, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 8, trend = FALSE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 8, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 4, trend = TRUE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 4, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 4, trend = FALSE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 4, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 2, trend = TRUE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 2, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 2, trend = FALSE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 2, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 1, trend = TRUE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 1, trend = TRUE, pastWeeksNotIncluded = 26, populationOffset = TRUE),
  list(w = 5,        noPeriods = 1, trend = FALSE, populationOffset = TRUE),
  list(w = 5,        noPeriods = 1, trend = FALSE, pastWeeksNotIncluded = 26, populationOffset = TRUE)
)


settings_who_a <- list(list(method = "median", n_years = 5),
                       list(method = "median", n_years = 6),
                       list(method = "median"),
                       list(method = "mean2sd", n_years = 5),
                       list(method = "mean2sd", n_years = 6),
                       list(method = "mean2sd"),
                       list(method = "percentile75", n_years = 5),
                       list(method = "percentile75", n_years = 6),
                       list(method = "percentile75"),
                       list(method = "percentile85", n_years = 5),
                       list(method = "percentile85", n_years = 6),
                       list(method = "percentile85"))



settings_far_orig <- list(
  #original defaults, no seasonality, no pop
  list(w = 3, b = 5, noPeriods = 1, trend = TRUE, weightsThreshold = 1, pThresholdTrend = 0.05, thresholdMethod = "delta", populationOffset = FALSE),
  #original defaults, w/ noPeriods = 4, no pop
  list(w = 3, b = 5, noPeriods = 4, trend = TRUE, weightsThreshold = 1, pThresholdTrend = 0.05, thresholdMethod = "delta", populationOffset = FALSE)) 
